name = "ClaudeMCPTools"
uuid = "b9bb1685-6a70-41d7-9793-2f9fb633d966"
version = "0.1.0"
authors = ["JuliaComputing"]

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
